### ISSUE TITLE
shutdown is strange

### ISSUE THREAD

**Issue by mgmax** [fau-fablab/FabLabKasse#105]
GUI shutdown works, but after pressing shutdown down the GUI restarts untill it is killed by the shutdown

**Comment by patkan** [comment]
This seems to be a problem outside of this code. When I start the code in a Vagrant-machine with a massively slowed down CPU our code prints `waiting for system poweroff` and the eventually the whole system shuts down. However on the real hardware the whole nodm-process seems to stop and then restart.
I could not yet reliably diagnose this particular event.

**Comment by mgmax** [comment]
This is a bug in nodm: https://github.com/spanezz/nodm/issues/5
Nodm is currently (more or less) unmaintained. Some extra work will be required for lightdm or sddm because they don't support `.xsession` files out of the box.
