### ISSUE TITLE
kassenbuch: encoding problems

### ISSUE THREAD

**Issue by sedrubal** [fau-fablab/FabLabKasse#106]
`kassenbuch.py` has problems with encodings. The input willnot be correctly checked or encoded and many parts of the code crash, when they get a wrong encoding...

**Comment by mgmax** [comment]
There is still a remaining problem with the address field in `client edit`: Create a client with unicode address, try to edit -> crashes:
```
Traceback (most recent call last):
  File "./kassenbuch.py", line 1486, in <module>
    main()
  File "./kassenbuch.py", line 1396, in main
    default_input=default
  File "./kassenbuch.py", line 1286, in fetch_input
    e=explanation, d=default_str)).decode(sys.stdin.encoding)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 36-41: ordinal not in range(128)
```
