### ISSUE TITLE
automatically call `cash verify` at start of payment

### ISSUE THREAD

**Issue by mgmax** [fau-fablab/FabLabKasse#115]
Before a payment starts, call `cash verify` and issue a warning to the log if it fails. This makes it easier to find the source of a cash state mismatch. (Only enable this if legacy_kassenbuch is used)

**Comment by patkan** [comment]
Optionally: do this while initiating the cash devices (but make sure there is no interference) since cash verify can take some time.

**Comment by patkan** [comment]
Or the other way round: do it after the user has payed. This way we don't increase the already long waiting period until payment has started. (And it makes more sense, since a defect will occur during payment, so we want to check afterwards)

**Comment by mgmax** [comment]
I agree that checking it afterwards is more helpful.

**Comment by mgmax** [comment]
feature will be removed
