### ISSUE TITLE
Quittungsdrucker druckt '?'

### ISSUE THREAD

**Issue by sedrubal** [fau-fablab/FabLabKasse#116]
Z.B. bei "Sechskantmutter DIN 934 ‐ M2 ‐ 8" (0522) kam "?Sechskantmutter DIN 934 ? M2" als Produktname raus. Vor Allem das '?' am Anfang ist komisch.

**Comment by mgmax** [comment]
Das sind non-printing unicode Zeichen. Alles das nicht in den Druckerzeichensatz umgesetzt werden kann wird zu sowas.

**Comment by patkan** [comment]
Man kann statt einem ? am Drucker auch afaik Leerzeichen konfigurieren. Ansonsten wird das handling von anderen codepages mit Python escpos in Version 1.1 besser.
Trotzdem wird man solche Zeichen auf unserer Seite entfernen müssen. (Und woher das Zeichen ganz vorne kommt kann man mal ergründen. Ich würde auf copy pasta tippen.)
