### ISSUE TITLE
reaction to jams

### ISSUE THREAD

**Issue by patkan** [fau-fablab/FabLabKasse#124]
Currently when a jam occurs the terminal simply waits forever and does not indicate the condition.

The terminal should recognize such a condition and then display a warning and maybe even shutdown the terminal.

**Comment by mgmax** [comment]
I don't think that the MDB protocol allows querying this state reliably. AFAIR a warning flag is sent only once, but this needs to be looked up in the MDB spec.

**Comment by mgmax** [comment]
Regarding the banknote reader: Yes, that would be possible, although changes in the device driver infrastructure would be required :-(

**Comment by patkan** [comment]
banknote handling is dropped
