### ISSUE TITLE
Münzer Licht ging an, obwohl keine Münzen zurückgegeben wurden

### ISSUE THREAD

**Issue by sedrubal** [fau-fablab/FabLabKasse#132]
Gerade hat jemand bezahlt und es wurde ein Schein zurück gegeben. Danach ging das Licht vom Münzer an, obwohl dieser gar nicht am Rückgabeprozess beteiligt war. Ist das gewollt?

**Comment by mgmax** [comment]
Das ist etwas hingefrickelt, kann durchaus ab und zu sein. wontfix.

**Comment by mgmax** [comment]
WONTFIX.
