### ISSUE TITLE
Add option to donate a custom amount in "Willst du das Rückgeld spenden?"-view

### ISSUE THREAD

**Issue by sedrubal** [fau-fablab/FabLabKasse#133]
The donate view proposes some amounts to donate. But if one wants to donate another amount, there is no way to do this except paying back all the money and the do a new payment. Can we add a Numeric-up-down to insert a custom amount to donate?

**Comment by patkan** [comment]
I am not sure. If one wants to Sonate a specific amount you could always add that amount manually before checkout.
Of course this hinders opportunistic donation of a specific amount, but I suppose that if you exactly know what you want to Sonate then you would enter that.

**Comment by sedrubal** [comment]
Theoretical one could do that. But I experienced it now and then that people asked afterwards how they can donate.

**Comment by mgmax** [comment]
feature is closed
