### ISSUE TITLE
Refactoring to python3

### ISSUE THREAD

**Issue by sedrubal** [fau-fablab/FabLabKasse#140]
I think, it's very important to port this project to `python3`. To make this step a bit simpler I would suggest to make it python3 only and drop `python2` support if needed.
There are many reasons, e.g.:
- unicode problems in `kassenbuch.py` :exclamation: :exclamation: :exclamation: 
- prepare FabLabKasse for the future
- get rid of ugly code
- more fun while coding
- ...

I think this only takes one day of hard work and it will be done.

**Comment by sedrubal** [comment]
There are some tools which can help and do the standard refactoring:
- `2to3`: does drop python2 support and port to python3 only code
- `python-modernize`: makes compatible code and looks quite nice

**Comment by sedrubal** [comment]
https://github.com/osiell/oerplib/issues/21

**Comment by mgmax** [comment]
well, the new odoorpc doesn't support OpenERP 7, so we are stuck here.

**Comment by sedrubal** [comment]
> well, the new odoorpc doesn't support OpenERP 7, so we are stuck here.

You're right. But I think we should upgrade to a newer version of odoo anyway. Oerp7 and oerplib are both not maintained and EOL.

https://www.odoo.com/page/odoo-long-term-support

**Comment by mgmax** [comment]
superseded by #162
