### ISSUE TITLE
faucard.py hardcoded DB name in finishLog

### ISSUE THREAD

**Issue by mgmax** [fau-fablab/FabLabKasse#148]
I just stumbled upon this:

Compare
https://github.com/fau-fablab/FabLabKasse/blob/676741f46dc9e45a00ec71fe00fc29e4b1fe8e44/FabLabKasse/faucardPayment/faucard.py#L131
and
https://github.com/fau-fablab/FabLabKasse/blob/676741f46dc9e45a00ec71fe00fc29e4b1fe8e44/FabLabKasse/faucardPayment/faucard.py#L120

**Comment by BDrescher** [comment]
Has been fixed in the recent commit at branch faucard_path1
