### ISSUE TITLE
Setup fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by mgmax** [fau-fablab/FabLabKasse#152]
Running the Vagrant setup with "ubuntu/bionic64" causes this error: https://github.com/pyca/cryptography/issues/4020

Best guess: Recent versions of python-cryptography (used by `requests`) are incompatible with the `enum` library, but wants the newer `enum34` which has a slightly different interface. This is a problem because FAUCardPayment uses `enum`.

- [x] rewrite FAUCardPayment to use `enum34`  (and test it thoroughly!)
- [ ] change requirements.txt
- [ ] update Vagrantfile to "ubuntu/bionic64" and test it

**Comment by BDrescher** [comment]
Hi,
I've looked into the code and as far as i can see, there should be no syntax errors. This is what i did so far: 

 -> testing by starting the programm (no error) 
 -> go through all code and test usage scenarios manually

The Enum usage in FAUCardPayment is mostly hardcoded, all asserts check for isinstance(int, Status/Info). SQLite storage is in int, but there is no loading from SQLite -> no int to Enum casting.

Could someone maybe just replace enum with enum34 and see if error still occurs?

€: Tried to setup vagrant for ubuntu/bionic64 but it keeps giving me 'The box ... could not be found'

**Comment by BDrescher** [comment]
Hey, 
I am replying once again as I know wether a edited comment will trigger a notification. For my reply see the message above.

**Comment by mgmax** [comment]
The vagrant box definitely exists: https://app.vagrantup.com/ubuntu/boxes/bionic64
I created the `fix-152-test` branch which uses `enum34` and `ubuntu/bionic64`, it does not crash. Because I don't have the real payment hardware, I get a connection error message as expected. I don't know how to test it further without real hardware.

**Comment by BDrescher** [comment]
I do not doubt it exists, yet it failed to run with me having little knowledge on vagrant. As soon as I have Access and time to the hardware, I will test the branch.

**Comment by mgmax** [comment]
I found out that we've been using `enum34` on the production system all the time, and the code would never have worked with the old `enum`. So the FAUCard code does not need to be changed, only `requirements.txt` was wrong.

**Comment by mgmax** [comment]
should be fixed
