### ISSUE TITLE
Migration to Python 3

### ISSUE THREAD

**Issue by patkan** [fau-fablab/FabLabKasse#162]
We try to modernize the terminal

- [x] add formatting
- [x] parallel task: add import for json @phdoerfler 
- [x] drop all irrelevant modules, likely
   - [x] cash payment - @mgmax 
   - [x] flickcharm? (port? find alternative? native?)
   - [x] escpos as module (take in as dependency)
   - [x] naughtystrings? @mgmax 
   - [x] processhelper
   - [x] shopping-backend oerp @patkan 
   - [x] shopping cart from app @mgmax 
   - [x] checkcartafterimport
   - [x] loadfrommobileapp
   - [x] payup manual dialog --> DO NOT remove, needed for testing because FAUcard is not testable without HW
   - [x] statistics dialog
 - [x] migrate to new py3 configparser with https://pypi.org/project/configparser/
 - [x] futurize to stage 2 (`futurize -wn --stage2 .`) (or not, this might produce horrible code, might have to do it manually) --> no longer needed???
 - [x] create a "software emulator" for FAUCard magpos terminal?
 - [x] update FAUCard stuff
 - [ ] find out why every provisioning a new locale is generated :grin: 
 - [x] module by module: import future and make py2/3 compatible
 - [x] drop python2 support
 - [ ] update to most recent version of python-escpos (and configure for our printer)
 - [ ] bonus: simplify code with native py3 syntax (f-strings etc.)
 - [x] install python3 pip into the VM
 - [x] update to newest black style (once we are on py3)
 - [ ] check documentary build with GitHub action
- [x] migrate pyqt to something more modern
  - [x] clarify: what is "more modern", what is the issue?
- [x] get rid of all "python2.7" references (exception: importProdukteOERP.py)
- [x] fix kassenbuch.py
- [x] manually test (and possibly fix) standalone scripts
  - [x]  logWatchAndCleanup
  - [x]  dummy-printserver
  - [x] exportConsumptionMoney
- [ ] fix and improve tests
  - [x] add one basic unittest for calling kassenbuch.py via shell (tests for the python API are already in test_kassenbuch.py, but there are none for the shell command)
  - [x] fix run_unittests, ensure it actually runs the tests
  - [ ] add basic unittests for other standalone scripts
  - [x] setup github action
- [ ] cleanup documentation, README, etc
- [x] remove all Py2 dependencies from install_debian.sh once importProdukteOERP is gone
- [x] then bump Vagrantfile to newest Debian stable
- [x] package black (e.g. shell script that sets up virtualenv and blackens everything, or automated with tox)

**Comment by patkan** [comment]
read json in https://github.com/fau-fablab/FabLabKasse/blob/5b46df6c4480f029d3fd08d9f9fe0d67f948ef1d/FabLabKasse/shopping/backend/legacy_offline_kassenbuch.py#L40?

**Comment by mgmax** [comment]
https://brain.fablab.fau.de/build/pricelist/price_list-Alle_Produkte.html.json

**Comment by patkan** [comment]
Philipp: looks into the produkt loader
Patrick: look into the qt bindings

**Comment by phdoerfler** [comment]
running vagrant up, amongst the many lines of output there's one line that stands out:
```
default: importlib-metadata 2.1.3 has requirement configparser>=3.5; python_version < "3", but you'll have configparser 3.5.0b2 which is incompatible.
```
Does that concern us?

**Comment by mgmax** [comment]
Best guess: Importlib is a leftover Python 2 dependency ("python < 3"), now it is already in the Python 3 standard library and must be removed from requirements.txt.
