### ISSUE TITLE
Unicode encoding in Kassenzettel

### ISSUE THREAD

**Issue by vale** [fau-fablab/FabLabKasse#166]
Broken Unicode characters in Kassenzettel see emailed Scan of Kassenzettel on Kasse@fablab.fau.de

**Comment by qugebert** [comment]
https://user.fablab.fau.de/~ow13ukic/Unicode_Bug.pdf

**Comment by patkan** [comment]
I will have a look, unless somebody else is on this.

**Comment by qugebert** [comment]
Related issue: https://github.com/fau-fablab/FabLabKasse/issues/116
