### ISSUE TITLE
payment via mobile app

### ISSUE THREAD

**Issue by mgmax** [fau-fablab/FabLabKasse#17]
- [x] dummy code for workflow
- [x] HTTP JSON connection: polling and fetching cart 
- [x] make configurable, document all settings: enable, server, app-url, etc.
- [x] document interface to server
- [x] test it
- [x] improve exception handling:
  - [x] server down
  - [x] Wenn App Server nicht erreichbar, kommt keine Fehlermeldung .
    - [x] Und beim Abbrechen hängt sich die GUI auf. 
  - [x] exit cart importing on error **TODO**
- [x] sanity checks
  - [x] filter invalid answers **TODO**
  - [x] filter broken JSONs
    - [x] don't add products with negative prices -> WONTFIX, user could do this anyway
  - [x] don't import non existing products
- [x] app-server: add API key as "password protection"
- [x] app-server: forbid updating already used cart ids
- [x] #54 app-server: use https

**Comment by mgmax** [comment]
Prinzipiell geht es jetzt, aber man sollte es noch ausführlich testen, insb. die oben beschriebenen doofen Fälle. Ohne echtes Gerät geht das Testen aber nicht gescheit, weil man da nicht den QRCode einlesen kann.

**Comment by sedrubal** [comment]
wow das geht echt gut :D

**Comment by sedrubal** [comment]
allerdings verwirrt der 2. QR Code und das Verhalten der App ist nicht schön, wenn man aus Versehen den unteren einscannt... Vllt. erst einblenden, wenn man nen Button drückt?

**Comment by sedrubal** [comment]
Wenn die Kasse aufgrund eines Fehlers abstürtzt, bekommt das die App nicht mit. Vielleicht will man auf Kurz oder Lang einen "background Worker" einbauen, der als eigenständiger Prozess kritische Tasks ordentlich verarbeitet und nicht so leicht abstürtzt, wie der Rest. Der könnte dann z.B. dem Server den Absturz melden und in der App kommt eine Erinnerung, dass man den Fehler melden will...

**Comment by mgmax** [comment]
Wenn die Kasse mitten im Bezahlen abstürzt, ist die Rückmeldung an die 
App das geringste Problem daran...

**Comment by mgmax** [comment]
@sedrubal der QR Dialog ist jetzt etwas schöner. Den Rest überlasse ich dir als Qt-Lernaufgabe :)

**Comment by sedrubal** [comment]
:+1:

**Comment by sedrubal** [comment]
App Bezahlung scheint jetzt gar nicht mehr zu gehen? Die Kasse pollt die ganze Zeit, aber bekommt keinen Warenkorb vom Server. gibt's da eig. nen Timeout, dass nicht unendlich pollt?

**Comment by nightvisi0n** [comment]
@sedrubal Funktioniert bei mir auch seit vorgestern nicht mehr.

**Comment by mgmax** [comment]
mit einer alten Version der App ca vom 27.6. (als debug build, fest auf code 1234 gestellt) geht es bei mir weiterhin. Liegt also wohl nicht an unserem Code.

**Comment by mgmax** [comment]
@jneureuther @sedrubal  könnt ihr mal die App gegen die "Referenzimplementierung" für das Kassenterminal-API testen?
http://ec2-52-28-16-59.eu-central-1.compute.amazonaws.com/checkoutDummy/

**Comment by nightvisi0n** [comment]
@mgmax habe gerade die aktuelle Developmentversion[1] der App gegen die "Referenzimplementierung" getestet, funktioniert nicht.

[1] https://github.com/FAU-Inf2/fablab-android/commit/dfe9ce1562dc6a872a630158c3f5077f7394d71c

**Comment by mgmax** [comment]
Ich hab letztens eine Fehlerbehandlung für nicht existierende Produkte ergänzt. Beim Testen sollten jetzt eigentlich (TM) keine Abstürze mehr auftreten, außer es wurde irgendwo was aus Versehen nicht abgefangen.

**Comment by sedrubal** [comment]
- [x] Eine falsche app URL, von der `Error 404` zurück kommt wird nicht als falsche URL erkannt.

**Comment by sedrubal** [comment]
- Wenn App Server nicht erreichbar, kommt keine Fehlermeldung
  - Und beim Abbrechen hängt sich die GUI auf. 

@sedrubal: Anmerkung Patrick: Kannst du bitte Schritte zum Nachvollziehen aufzeigen? Ich konnte diesen Fehler heute nicht reproduzieren.

@patkan: Schritte zum Aufhängen:
- Suche IP/URL, die es nicht gibt; gerade funktionierte `123.234.165.142`
- In config eintragen
- Import starten und abbrechen

Fehlermeldung erscheint mittlerweile im `stdout`, aber nicht in der GUI

(Punkte zum Abhaken hab ich oben eingetragen)

**Comment by patkan** [comment]
Wie will man unterscheiden zwischen zB Server kaputt und Server wartet noch?

**Comment by sedrubal** [comment]
Im Idealfall schon, aber dann müsste ein funktionierender Server irgendwas zurückgeben...

**Comment by mgmax** [comment]
@sedrubal  kann ich nur bedingt nachvollziehen. Wenn ich http://4.5.6.7/ als URL einstelle, braucht die HTTP-Anfrage immer 10s bis zum Timeout und währenddessen blockiert die GUI. Mit 10s Verzögerung reagiert sie aber auf Eingaben. Ich weiß nicht ob man bei cart_model.load() einen kleineren Timeout einbauen will, aber eigentlich ist das auch egal.

**Comment by mgmax** [comment]
@patkan habe noch die Exception-Info in die Meldung dazu gepackt und es nach development gepusht

**Comment by patkan** [comment]
:+1:

**Comment by sedrubal** [comment]
@mgmax in den 10 Sekunden sollte die GUI nicht blockieren... Ich sag nur MVVM ;) Aber ich denke, das sind jetzt mehr Schmerzen, als dass es was bringt...

**Comment by sedrubal** [comment]
Negative Stückzahlen lassen das Terminal sterben.

Test-JSON:

``` json
{"cartCode":"2638286801899210886","items":[{"id":44,"productId":"9011","amount":-5.0}],"status":"PENDING","pushId":"000","sentToServer":1437080976055}
```

**Comment by sedrubal** [comment]
Dazu kommt:
- Alle Antworten (http Status Code `200` aber sonst kein sinnvoller Inhalt) führen nicht dazu, dass der Vorgang abgebrochen wird
- Erweiterung zu Kommentar von gerade: JSONs, die nicht valide sind, bringen das Terminal zum Absturz

ist oben in der Liste ergänzt...

(Testen kann man sowas gut, wenn man als AppServer `http://0.0.0.0:8000` in die config einträgt und dann irgendwo mit `python -m SimpleHTTPServer` einen Webserver startet. Anhand der stdout-Ausgaben kann man in dem Ordner, wo der Server läuft, die Datei reinlegen, wonach das Terminal gerade sucht)

**Comment by sedrubal** [comment]
Zum Testen kann - wie gesagt - `SimpleHTTPServer` verwendet werden. Dazu hab ich noch dieses Skript gebaut, mit dem man schnell und einfach ein JSON mit passender cart_id / cartCode bauen kann: `./makeCart.py <id>`

``` python
#!/usr/bin/env python

import json
from sys import argv
import time

id = int(argv[1])

data = {}
data["cartCode"] = id
data["items"] = []

product = {}
product["id"] = 44
product["productId"] = "9011"
product["amount"] = "5.0"

data["items"].append(product)
data["status"] = "PENDING"
data["pushId"] = "000"
data["sendToServer"] = int(time.time())

f = open(str(id), "w")
f.write(json.dumps(data))
f.close()
```

**Comment by patkan** [comment]
Für "Wenn App Server nicht erreichbar, kommt keine Fehlermeldung . " könnte man noch die Anzahl der Fehlversuche zählen und nach n abbrechen. Oder wontfix, Meinungen?

**Comment by patkan** [comment]
@mgmax, @sedrubal, @jneureuther  Ich würde sagen wir sind fertig :-)
Schaut mal bitte drüber. Falls alles passt, können wir das Feature schon jetzt anschalten
