### ISSUE TITLE
kassenbuch.py export macht Festplatte voll

### ISSUE THREAD

**Issue by qugebert** [fau-fablab/FabLabKasse#170]
Ich reiche noch kurz eine etwas vernünftigere Beschreibung nach:

Es war aufgefallen, dass die "Kassenbuch Mai" - Mail ausgeblieben ist.
Nachdem ich heute separat die https://github.com/fau-fablab/FabLabKasse-interna/blob/master/mail-monthly.sh aufgerufen hatte kam sinngemäß eine Fehlermeldung, dass die Festplatte voll sei. 

Nach kurzer Suche stellte sich heraus, dass die beiden temporären Dateien, die von o.g. Script erzeugt wurden wohl 63GB und 20GB groß sind. 

Auch wird die --from Angabe wohl ignoriert, also der gesamt Zeitraum wurde exportiert, aber selbst der gesamte Zeitraum dürfte nicht ansatzweise so groß werden.

**Comment by mgmax** [comment]
wurde mittlerweile behoben
