### ISSUE TITLE
kassenbuch.py: PIN 0000 deaktiviert nicht den Account

### ISSUE THREAD

**Issue by patkan** [fau-fablab/FabLabKasse#19]
Gemäß [Zeile 792 in kassenbuch.py](https://github.com/fau-fablab/FabLabKasse/blob/61dc18d302ad0bb61808a0a60aa4c243ffca4f59/FabLabKasse/kassenbuch.py#L792) bedeutet eine PIN `0000`, dass der Account deaktiviert ist.

Trotzdem ist ein Buchen auf die Kundennummer möglich.

**Comment by sedrubal** [comment]
@patkan warum ich? :D

**Comment by patkan** [comment]
Hab mal gehört, das würde Projekte voran bringen die zu assignen :-P
