### ISSUE TITLE
automatic class documentation (sphinx)

### ISSUE THREAD

**Issue by patkan** [fau-fablab/FabLabKasse#24]
Create automatic class overview by parsing the docstrings. Search an appropriate tool.

**Comment by sedrubal** [comment]
https://pypi.python.org/pypi/Sphinx/

**Comment by patkan** [comment]
Will man das lieber als epydoc? Kann man gerne machen. Ich habe nur gelesen es wäre schwieriger zum aufsetzen und fällt manchmal eher zusammen (da es importiert und nicht parst oder so)

**Comment by patkan** [comment]
Wenn du möchtest, dann kannst du das gerne übernehmen @sedrubal.
Es muss nicht epydoc sein, gibt nur folgende Constraints:
- Es sollte auf Knopfdruck bauen und nicht ultra hässlich in der Wartung sein
- Das Markup muss von PyCharm verstanden werden. PyCharm kann das Markup parsen und dann das angeblich als TypeHints verwenden. Siehe dazu [Type Hinting in PyCharm](https://www.jetbrains.com/pycharm/help/type-hinting-in-pycharm.html)

**Comment by sedrubal** [comment]
achso, ich hab keine Erfahrung, hab bis jetzt aber nur sphinx gesehen. Ich möchte das aber nicht übernehmen ;)

**Comment by mgmax** [comment]
man müsste auch mit gucken, ob es eine sinnvolle design-by-contract sowie unittest Möglichkeit gibt. Diese Libs erfordern teilweise eine bestimmte Art von docstrings, d.h. man schreibt beispielsweise in die Doku "Example: foo(42) = 43" und dann testet der unittester, ob dem so ist.

**Comment by patkan** [comment]
Ganz hübsch, aber auch simpel ist [doctest](https://docs.python.org/2/library/doctest.html).

**Comment by cod3monk** [comment]
Testen und Dokumentation sind eigentlich zwei verschiedene dinge:
sphinx ist quasi Standard für Dokumentation und kann sowohl docstrings parsen als auch unabhänige Dateien um z.B. Tutorials, Howtos, Installationsanlteitungen zu erstellen. epydoc wird nicht mehr weiterentwickelt und pdoc ist als Nachfolger gedacht.
doctest ist hübsch und sehr einfach, kann aber nicht mehr als Einzeiler (bzw. will man nicht für mehr verwenden). Für alles andere brauch man was sinnvolles, zum Beispiel unittest.

**Comment by mgmax** [comment]
@sedrubal  sphinx sieht gut aus, magst du das mal ausprobieren?

unabhängig davon müssen wir uns dann noch auf eine Konvention für die Typen einigen. Die von Patrick verlinkte finde ich gut menschenlesbar: https://www.jetbrains.com/pycharm/help/type-hinting-in-pycharm.html#d296375e18526

**Comment by sedrubal** [comment]
hab gerade sphinx ausprobiert, aber ich hab es nicht verstanden, wie man das konfiguriert bekommt. Wie wärs mit doxygen?

**Comment by patkan** [comment]
Doxygen hat auch was. Das Argument für sphinx wäre halt, dass es de-facto-Standard ist.
reStructuredText kann doxygen sauber und komplett parsen?
Ansonsten würde ich am liebsten noch ein paar andere Meinungen sammeln.

**Comment by sedrubal** [comment]
Doxygen kann das nur mit doxypy Filter glaub ich. Ob's vollständig funktioniert, weiß ich nicht.

Wenn sich jemand um Sphinx kümmern mag, bin ich ihm nicht böse. Allerdings hab ich's nicht hin bekommen und es soll auch seine Eigenheiten und Probleme haben (https://stackoverflow.com/questions/4126421/how-to-document-python-code-epydoc-doxygen-sphinx#answer-8004864)

**Comment by patkan** [comment]
Ich hab sphinx-apidoc gefunden und damit das hier erzeugt: eb864b54f87bf0a2faaa27bb475c1ce315111d7d
Das ist atm aber noch ziemlich kaputt...
Entweder hab ich das Tool falsch verwendet, oder es ist ungeeignet oder Unfug :-)

**Comment by sedrubal** [comment]
also es schaut irgendwie weder gut aus, noch funktioniert es bei mir. Es scheint so, als ob entweder ich oder Sphinx _automatische_ Dokumentation nicht verstanden hab...

**Comment by patkan** [comment]
Da muss ich dir Recht geben.
Das apidoc-Skript erzeugt zwar alles automatisch, aber so wirklich toll ist das nicht. Eigentlich müsste das ja auch die automodule-Anweisung erledigen, wenn ich das richtig verstanden habe. Damit hab ich aber noch gar nichts hinbekommen.
Ansonsten finde ich sieht es ganz hübsch aus, bis auf den Fakt, dass das toc Kraut und Rüben ist.

Ein anderes Problem ist noch, dass der Code importierbar sein muss. Und aus noch nicht näher erkannten Gründen, wirft das Sphinx bei 75 Modulen Warnings und stirbt.

**Comment by mgmax** [comment]
so, läuft jetzt. Fehlt noch irgendein buildserver. readthedocs.org würde das erschlagen, wollte für meinen Geschmack aber zuviele Zugriffsrechte auf github.
