### ISSUE TITLE
design pattern: design-by-contract + inheritance

### ISSUE THREAD

**Issue by mgmax** [fau-fablab/FabLabKasse#27]
how should this case be handled?
- an abstract baseclass, like shopping, documents certain "contracts" that an implementation must follow
- this should somehow be checked with assertions before and after the function call, but without copying these assertions to every implementation

pseudocode: 

```
@abstractmethod
def foo():
    assert everything_is_nice()
    ... here comes the subclass implementation ...
    assert everything_is_still_nice()
```

like here: https://github.com/fau-fablab/FabLabKasse/blob/45e39abd2ef67c019e71ffa8b312cf9b30d849e0/FabLabKasse/shopping/backend/abstract.py#L293

**Comment by patkan** [comment]
I think unittests might be the solution.

Otherwise something like changing the abstract methods to wrappers and using abstract private function could be a (somewhat hacky) solution.

pseudocode:

``` python
def foo():
    assert everything_is_nice()
    _foo()
    assert everything_is_still_nice()

@abstractmethod:
def _foo():
    subclass implementation
```

**Comment by patkan** [comment]
pycontracts looks like the deal. It seemas to be supporting contracts and inheritance (see https://andreacensi.github.io/contracts/api/contracts.html#contracts.ContractsMeta)

**Comment by patkan** [comment]
Not directly what we want here, but maybe interesting nevertheless: https://hypothesis.readthedocs.org
