### ISSUE TITLE
wrong size of "Warenkorb aus App laden" button

### ISSUE THREAD

**Issue by nightvisi0n** [fau-fablab/FabLabKasse#29]
The attribute `minimumSize` is not correctly set.

![kt](https://cloud.githubusercontent.com/assets/4653434/8444757/fec48b3e-1f94-11e5-8f0e-9ec6f8489268.png)

**Comment by mgmax** [comment]
Das per minimumSize zu lösen, ist nicht die richtige Lösung - je nach 
DPI haut das ja nicht hin. Dafür gibt es sizePolicy etc.

**Comment by mgmax** [comment]
gescheit gelöst per e7425b6c05e2d1d53eb69d67e16903419f1a831c
