### ISSUE TITLE
Fenster maximiert starten

### ISSUE THREAD

**Issue by mgmax** [fau-fablab/FabLabKasse#30]
Bei der aktuellen Version vom Terminal sieht man unten den blauen
Hintergrund durch, da das Fenster nicht maximiert ist.

**Comment by sedrubal** [comment]
bei mir startet nix maximiert :(

**Comment by mgmax** [comment]
komisch, du hast Recht...

**Comment by sedrubal** [comment]
Hab schon an mir gezweifelt ;)

**Comment by sedrubal** [comment]
top. Aber warum muss das so kompliziert sein?
