### ISSUE TITLE
rounding of subcent values

### ISSUE THREAD

**Issue by patkan** [fau-fablab/FabLabKasse#31]
Currently the sum of a cart woth subcent value is cut. Is rounding better?
for example:

```
2.985 becomes 2.98
proposal:
2.985 becomes 2.99
```

**Comment by mgmax** [comment]
`round()` behaves strangely:

```
>>> [round( i + Decimal("0.5"), 0) for i in range(10)]
[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]

>>> [round( (i + Decimal("0.5"))*Decimal("0.1000"), 1) for i in range(10)]
[0.1, 0.1, 0.3, 0.3, 0.5, 0.6, 0.7, 0.8, 0.8, 0.9]
```

we should implement something on our own in 
shopping.backend.abstract.AbstractShoppingBackend.get_current_total()

**Comment by patkan** [comment]
@mgmax `ROUND_HALF_UP` seems to do the trick.
I think this can be merged into development.

**Comment by mgmax** [comment]
@patkan  would be great if you could look at the latest comments I made to your commit and complete this soon, because it will fix the crashes from #46 .

**Comment by patkan** [comment]
I think 6655b1fb2ffa057a5211bdf6a85410f421127984 is ready for merging. Famous last words?

**Comment by mgmax** [comment]
looks good, merged.
