### ISSUE TITLE
Show last transaction after crash?

### ISSUE THREAD

**Issue by patkan** [fau-fablab/FabLabKasse#35]
The terminal automatically restarts on a software crash.
Would it be helpful to show the last transaction upon start?
How to detect an abnormal start (coming from a crash)?
Is there a benefit from showing this information?
Is there a risk? Basically the user cannot trust the kassenbuch at this point!

**Comment by sedrubal** [comment]
...or at least recover last shopping cart

**Comment by mgmax** [comment]
@patkan  I don't understand. Can you give an example how this should help?

Recovering the shopping cart is implicitly done by online shopping backends like OpenERP and not  possible for offline ones. Automatic error recovery is very difficult because after a crash you cannot assume anything.

**Comment by patkan** [comment]
I don't know how this could help neither. I just wanted to discuss this, but I think we can close this with wontfix, can't we?
