### ISSUE TITLE
Clear all button

### ISSUE THREAD

**Issue by tmaex** [fau-fablab/FabLabKasse#36]
A "clear all" button would be usefull in case of somebody left the terminal with a full cart.

It could be placed next to "Pay now"/"Jetzt zahlen" but then there should be a confirmation for confused users that wanted to pay.

**Comment by sedrubal** [comment]
:+1: and thanks for reporting.

There is always a good space on the right side below of the trash bin for deleting one product.

**Comment by patkan** [comment]
Maybe the top of the window is a good place. There will also be the button to fetch a cart from the app.
This is related to #3.

**Comment by mgmax** [comment]
placing it at the top is not really logical, you don't look for it there.
