### ISSUE TITLE
Relative Pfade ändern

### ISSUE THREAD

**Issue by sedrubal** [fau-fablab/FabLabKasse#39]
Da hat sich was eingeschlichen (`[...]/home/max/.designer[...]`):
- https://github.com/fau-fablab/FabLabKasse/blob/development/FabLabKasse/UI/PayupCashDialog.ui#L451
- https://github.com/fau-fablab/FabLabKasse/blob/development/FabLabKasse/UI/PayupCashDialog.ui#L471
- https://github.com/fau-fablab/FabLabKasse/blob/development/FabLabKasse/UI/PayupCashDialog.ui#L504

**Comment by mgmax** [comment]
scheint ein Bug in Qt Designer zu sein, der nicht weiter stört.

**Comment by sedrubal** [comment]
ok :)
