### ISSUE TITLE
Quittung bei Bezahlung durch Kundenkonto

### ISSUE THREAD

**Issue by sedrubal** [fau-fablab/FabLabKasse#48]
Warum gibt es keine Quittungen, wenn man mit einem Kundenkonto bezahlt?

**Comment by mgmax** [comment]
Weil es eine Rechnung nur für Geldfluss gibt, nicht für virtuelle Dinge. Für ein Kundenkonto wird z.B. später eine Sammel-Rechnung gestellt, oder es war nur ein Guthaben. In beiden Fällen wäre eine zusätzliche Rechnung über einen Einkauf dann eine doppelte Rechnungsstellung. 

Das ist auch so dokumentiert.
https://github.com/fau-fablab/FabLabKasse/blob/b4516af9dcbdf23c21b5156a8b0dcc70148d7d00/FabLabKasse/shopping/payment_methods.py#L180
