### ISSUE TITLE
accounting (legacy kassenbuch) testing

### ISSUE THREAD

**Issue by mgmax** [fau-fablab/FabLabKasse#5]
start with a clean checkout
follow the instructions (FAU specific ones) in TODO
test the "test case matrix" combinations specified there, incl receipt printing (use tools/dummy-printserver for testing)

reward:
- 1 cookie per bug
- 1 mate for the first accounting-related critical bug (wrong sum stored somewhere, half cents missing on receipt etc.)

**Comment by mgmax** [comment]
Genauere Auflistung der Testmatrix:

Vorbereitung:
- clean checkout (d.h. keine Datenbank, alte Dateien o.ä. rumliegend)
- config.ini.example nach config.ini kopieren, darin:
  - backend auf ...kassenbuch
  - ERP nutzer eintragen

_In allen Fällen_ schauen dass
1. der Kassenzettel sinnvoll rauskommt # lokaler Server: tools/dummy-printserver
2. kassenbuch.py die Buchung korrekt anzeigt 
3. bei Bargeld Automatenkasse: `./cash verify` zufrieden ist
   - [x] Kundenzahlung
     - hier kein Kassenzettel!
     - [x] genau passend eingezahlt
     - [x] abgebrochene Zahlung (soll nix verbucht werden)
     - [x] Schuldengrenze darf nicht überzogen werden können
     - [x] andere Fälle wie "zuwenig eingezahlt" müssen unmöglich sein (klar, gibt auch keine GUI dafür)
   - [x] Bargeldzahlung (automat.)
     - [x] Spende (Überzahlung)
     - [x] zuwenig Wechselgeld
     - [x] auf/abgerundet (krumme Centbeträge einkaufen) + dann "exakt" bezahlt
     - [x] abgebrochene Zahlung
     - [x] abgebrochene, nicht vollständig wieder rückzahlbare Zahlung
   - [x] Bargeldzahlung (manuell)
     - [x] zuwenig eingezahlt (soll unmögl. sein und nix verbucht werden)
     - [x] genau passend eingezahlt
     - [x] auf/abgerundet (krumme Centbeträge einkaufen) + dann "exakt" bezahlt
     - [x] Spende (Überzahlung)
     - [x] abgebrochene Zahlung

**Comment by mgmax** [comment]
so, jetzt ist die Liste sinnvoll abarbeitbar. Das mit den Cent-Bruchteilen in der DB hat hiermit eigentlich nix zu tun und kommt deshalb in ein extra Issue.

**Comment by patkan** [comment]
Ich habe den manuellen Zahlungspunkt getestet. Passt alles, allerdings gibt es ein unschönes Verhalten in kassenbuch.py. Dazu hab ich #18 angelegt.

**Comment by patkan** [comment]
Kontozahlung habe ich auch geprüft.

**Comment by patkan** [comment]
Automatenkasse ist jetzt auf Basis des ExampleServer auch durchgetestet.

**Comment by patkan** [comment]
@mgmax, @sedrubal, @jneureuther: wenn keiner mehr Einwände oder Bugs hat kann man den Issue hier schließen und damit den Milestone abschließen. Jay :+1:
