### ISSUE TITLE
flickcharm submodule uses ssh URL

### ISSUE THREAD

**Issue by mgmax** [fau-fablab/FabLabKasse#51]
- update INSTALLING with info that a github account is needed
- undo local changes on kassenterminal (currently uses https as workaround)

**Comment by patkan** [comment]
Which reasons do we have to not switch to https-checkout?
- you need a credential store, because ssh-key is not applicable
- two-factor-authentication users need a generated token

Are there more?
Do you still have these problems when using https only for the submodules (since the standard use case does exclude commiting in submodules).

**Comment by sedrubal** [comment]
Sorry, mal auf deutsch: das Problem an SSH remote URLs für submodules ist doch, dass nicht GitHub user keine Möglichkeit haben, sich das submodule ordentlich zu holen, drum sollte man https URLs verwenden, oder?

**Comment by patkan** [comment]
Ich glaub das hier können wir auch auf Deutsch machen, im Moment sind wir ja sowieso nicht international :-)
Jo, das ist es, würde ich sagen. Ich glaub dann ist es in Ordnung, wenn wir https für die submodules verwenden, oder?

**Comment by mgmax** [comment]
Ist halt nerviger für die Entwicklung. Vielleicht als Mittelweg dennoch 
eine ssh push-URL angeben?

**Comment by sedrubal** [comment]
warum nervig? Über https geht es doch noch einfacher, da man sich zum Pullen nicht anmelden muss...

**Comment by mgmax** [comment]
nervig, weil push nicht geht und SSL recht unsicher ist.

**Comment by cod3monk** [comment]
ssl unsicherer als ssh? ich weiß ja nicht. bei ssl gibt es zumindest theoretisch eine certificate authority, bei ssh muss man dem erst bestem glauben der vorbeikommt...

**Comment by sedrubal** [comment]
Allerdings sind submodules auch niemals zum Pushen da, sondern sollten nur passiv aktualisiert werden. Änderungen sollten ausschließlich in einem extra Clon (ggf. über ssh) geschehen - zumindest soweit das ich weiß...

Und zum Thema Sicherheit: Solange Commits nicht PGP signiert werden,... :P

**Comment by mgmax** [comment]
Nein. Mache ich bei VisiCut + LibLaserCut schon dauernd so, es hindert 
einen garnichts dran. In bestimmten Situationen (inkompatible Änderungen 
in Lib) kommst du garnicht drumherum.

**Comment by sedrubal** [comment]
Ok, hab mich auch nochmal informiert, dann hatte ich da einen falschen Eindruck. Aber mit extra Repos kann man auf jeden Fall das URL Problem lösen.

**Comment by patkan** [comment]
Man muss folgendes tun im Hauptverzeichnis des Repos:

```
cd FabLabKasse/libs/flickcharm/
git remote set-url origin https://github.com/fau-fablab/flickcharm-python.git
git remote set-url --push origin git@github.com:fau-fablab/flickcharm-python.git
```

Die Ausgabe von `git remote -v` sollte jetzt sein:

```
origin  https://github.com/fau-fablab/flickcharm-python.git (fetch)
origin  git@github.com:fau-fablab/flickcharm-python.git (push)
```

Jetzt stellt sich nur die Frage, wie man das in die submodule-config rein bekommt. So ist das nur eine lokale Änderung, die nicht im Repository landet.
Ich schau mal, ob sich das in `.gitmodules` anpassen lässt.

**Comment by patkan** [comment]
Soweit ich das jetzt gelesen habe, gibt es keine Möglichkeit, das fest zu setzen.
Am besten setzt man die default-url auf `https`, dann kann man mit einem `git remote set-url --push` die url richten bei Bedarf.
Alternativ schreibt man in seine `~/.gitconfig`:

```
[url "git@github.com:fau-fablab/"]
    pushInsteadOf = https://github.com/fau-fablab/
    pushInsteadOf = git://github.com/fau-fablab/
```

_UPDATE:_ ich hab den letzten Configblock etwas modifziert. Der sollte jetzt eigentlich alle fau-fablab URLs beim pushen passend umbiegen.
