### ISSUE TITLE
ADD support for other currencies

### ISSUE THREAD

**Issue by patkan** [fau-fablab/FabLabKasse#60]
This is relevant for use in other countries and as long as we know of no other users low priority.
- [ ] make the hardcoded money limits configurable since other courencies might have bigger values (for example Yen)
- [ ] maybe think of a way to test whether big values will crash the code somewhere
- [ ] make the currency-symbol configurable

**Comment by mgmax** [comment]
won't fix (we have enough other issues for the next years)
