### ISSUE TITLE
app-import-dialog only promotes the android app

### ISSUE THREAD

**Issue by patkan** [fau-fablab/FabLabKasse#69]
This dialog should be able to show several links.
Maybe by configuring them in the config and dynamically generating tabs with the QR-Codes or by showing a website that has the QRs pointing to the different Apps.

**Comment by patkan** [comment]
Possible solution:
Setup website and link to this website.
The website automagically detects the browser and shows the correct QR-Code for the device. Otherwise all App-Store-Links are shown.

**Comment by sedrubal** [comment]
where should we run the website? On our homepage or on macgyver? In `PHP` or in `Flask`? :smile:

**Comment by sedrubal** [comment]
https://fablab.fau.de/app/redirect.php ;)

**Comment by mgmax** [comment]
the background image should be fixed, the text is almost unreadable:

![Screenshot](https://cloud.githubusercontent.com/assets/1520891/10028470/fa067778-616c-11e5-9ef5-22236dd431eb.png)

**Comment by mgmax** [comment]
as soon as that is fixed: really cool!

**Comment by nightvisi0n** [comment]
fixed with https://github.com/fau-fablab/app-promotion-site/commit/62dcf31b5e331745d7ab5e80c2e453a2ac837703
