### ISSUE TITLE
unit-testing with naughty-strings

### ISSUE THREAD

**Issue by patkan** [fau-fablab/FabLabKasse#74]
Inject www.github.com/minimaxir/big-list-of-naughty-strings wherever it makes sense.

**Comment by patkan** [comment]
@sedrubal I think it does not make that much sense to inject these strings into the text input of the GUI.
At the moment I don't know how, however, we could try to inject it into the internal product database.

**Comment by sedrubal** [comment]
Yes, I also think, this is useless. You can close this issue ;)
