### ISSUE TITLE
Configure Landscape.io

### ISSUE THREAD

**Issue by patkan** [fau-fablab/FabLabKasse#82]
The landscape.io-reviews can be improved by creating a config-file.
Otherwise one could review tool alternatives and discard landscape.io

**Comment by sedrubal** [comment]
:+1: landscapeio looks good.

But I dont't know any alternatives (aside from a proper Python IDE or pylint ;) )

**Comment by patkan** [comment]
Seems to look good.
Somewhen at a later point we should have a look at which suite we can discard again.
