### ISSUE TITLE
superfluos assert in cashState

### ISSUE THREAD

**Issue by patkan** [fau-fablab/FabLabKasse#99]
What is the purpose of the assert in https://github.com/fau-fablab/FabLabKasse/blob/52b2b603c7c681be5f852aa5415b345e2b477720/FabLabKasse/cashPayment/cashState.py#L139-L140 ?
For me this seems like checking whether `3 != 4`.
@mgmax I think this is your code, isn't it?

**Comment by mgmax** [comment]
well, `CashState` is not as simple as `int`, so where's the problem with 
some sanity check that effectively is
`assert other.__neg__().__neg__() == other` ? I think this is better 
than just a dead comment somewhere telling you how it should be. Here 
you have the guarantee how it must be (or it will crash).
